name: AudioVisualizerApp
options:
  bundleIdPrefix: com.audiovisualizer
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 1.0.0
  AudioVisualizer:
    path: .

targets:
  AudioVisualizerApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AudioVisualizerApp
    info:
      path: AudioVisualizerApp/Info.plist
      properties:
        CFBundleDisplayName: Audio Visualizer
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "This app needs access to your microphone to visualize live audio waveforms."
        MTLCaptureEnabled: true
    dependencies:
      - package: AudioVisualizer
        product: AudioVisualizer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.audiovisualizer.app
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
        SUPPORTS_MACCATALYST: YES
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES

